In [56]:
import pandas as pd
import numpy as np
df = pd.read_csv('LA_County_Resturants_CensusTracts.csv', encoding='utf-8')
df = pd.concat([df, pd.get_dummies(df['category1'])], axis=1)

df['category1'].value_counts()[:25]

Mexican                   263
American (New)            105
Food Trucks                99
Cafes                      69
Coffee & Tea               67
Italian                    65
Breakfast & Brunch         62
Burgers                    60
Japanese                   53
Korean                     51
Mediterranean              45
American (Traditional)     45
Seafood                    40
Chinese                    35
Pizza                      33
Sandwiches                 31
Bakeries                   31
Thai                       30
Barbeque                   30
Tacos                      28
Ramen                      28
Sushi Bars                 27
Bars                       24
Latin American             22
Asian Fusion               20
Name: category1, dtype: int64

In [53]:
c_grp = df.groupby('CensusTract')
# pull averages from grouped datasets, do that to all the numerical columns
rating_averages = c_grp['rating'].mean()

In [62]:
#I'll handle the categories and string variables
total_resturants = c_grp['category1'].count().rename('total_resturants')

types_rest = c_grp[['Mexican', 'American (New)','Coffee & Tea','Italian',
                    'Breakfast & Brunch', 'Burgers','Japanese','Korean','Mediterranean',
                    'Chinese','Pizza','Bars','Ramen' ]].sum()

ydf = pd.concat([c_grp.mean()[['rating','review_count']], total_resturants, types_rest], axis=1)

In [64]:
c_df = pd.read_csv('census_data.csv')

In [46]:
import matplot.pyplot as plt
import seaborn as sns

heatdf

sns.heatmap()

,count,unique,top,freq
CensusTract,,,,
6.037101e+09,2,1,[],2
6.037101e+09,1,1,"['delivery', 'pickup']",1
6.037101e+09,1,1,[],1
6.037102e+09,1,1,[],1
6.037103e+09,1,1,[],1
6.037103e+09,1,1,[],1
6.037104e+09,2,1,[],2
6.037104e+09,2,1,[],2
6.037104e+09,2,1,[],2
6.037104e+09,2,1,[],2
6.037104e+09,1,1,[],1
6.037104e+09,1,1,[],1
6.037105e+09,2,1,[],2
6.037105e+09,1,1,[],1
6.037105e+09,4,1,[],4
6.037105e+09,2,2,"['delivery', 'pickup', 'restaurant_reservation']",1
6.037105e+09,3,1,[],3
6.037105e+09,1,1,[],1
6.037105e+09,1,1,"['delivery', 'pickup']",1
6.037106e+09,1,1,[],1
6.037106e+09,1,1,[],1
6.037106e+09,2,1,[],2
6.037106e+09,1,1,"['delivery', 'pickup', 'restaurant_reservation']",1
6.037106e+09,1,1,[],1
6.037106e+09,1,1,[],1
6.037107e+09,1,1,"['pickup', 'delivery']",1
6.037107e+09,1,1,[],1
6.037108e+09,1,1,[],1
6.037109e+09,1,1,[],1
6.037110e+09,1,1,[],1
...,...,...,...,...
6.037533e+09,7,1,[],7
6.037535e+09,2,1,[],2
6.037535e+09,1,1,['pickup'],1
6.037535e+09,2,1,[],2
6.037535e+09,1,1,[],1
6.037541e+09,2,2,['pickup'],1
6.037541e+09,1,1,[],1
6.037554e+09,1,1,[],1
6.037600e+09,1,1,[],1
6.037600e+09,1,1,[],1
6.037602e+09,1,1,[],1
6.037603e+09,2,1,[],2
6.037700e+09,1,1,"['pickup', 'delivery']",1
6.037700e+09,2,1,[],2
6.037700e+09,1,1,[],1
6.037701e+09,1,1,[],1
6.037702e+09,1,1,[],1
6.037702e+09,1,1,[],1
6.037703e+09,1,1,[],1
6.037703e+09,12,4,[],8
6.037703e+09,1,1,[],1
6.037703e+09,6,3,[],3
6.037920e+09,1,1,[],1
6.037920e+09,1,1,"['delivery', 'pickup']",1
6.037980e+09,3,1,[],3
6.037980e+09,1,1,[],1
6.037980e+09,1,1,[],1
6.037980e+09,1,1,[],1
6.037980e+09,24,4,[],21
6.037980e+09,4,1,[],4